### PR TITLE
Selective setting rendering and seach function

### PR DESCRIPTION
**Pull request by mProjectsCode**
What id did:
- declutter some of the big files by extracting classes out into their own files
- rework the setting rendering
- settings now get parsed into a recursive structure
- search bar that allows filtering of the settings

What is still missing from this PR:
- ~~integration with javalents settings search plugin~~
- code comments

What no longer works:
- to get the color picker to be performant I had to hide it with `display: none` when not active. This breaks the fade in and out animation

What changed in terms of layout (important for theme devs)
- all root-level setting sections/headings are now contained in one div to separate them from the header
- the heading bar now has a search bar
- I am considering replacing the obsidian setting component that is used as a header with a simple flexbox div

### CODE REVIEW

**Comment by mProjectsCode** [comment]
I opened this as a draft PR, as there are some things still missing.

And PR id 100 \o/

**Comment by mgmeyers** [comment]
@mProjectsCode Thanks for all your work on this. It all seems to be working well in my tests. I've merged your branch in manually rather than through this PR as there were some circular dependencies that needed fixing. This should be released as version 1.0.0 shortly

**Comment by mProjectsCode** [comment]
ok. 

>  I've merged your branch in manually rather than through this PR as there were some circular dependencies that needed fixing.

This means that the PR will not show up in my contributions (and I won't show up as a contributor on this repo), but that's not too big of a deal for me.

**Comment by mgmeyers** [comment]
Ah, sorry, didn't think about that! Hmm, I do see you in the contributors list here: https://github.com/mgmeyers/obsidian-style-settings/graphs/contributors

**Comment by mProjectsCode** [comment]
oh, i didn't see that. Well then forget everything I said xD

**Pull request closed without merging**
