### PR TITLE
Add `hsl-split-decimal` color formatting option

### LINKED ISSUE #91: FR: Add a unitless formatting version of `hsl-split`
Add a color formatting option like `hsl-split`, but without the %-signs

CSS `calc()` doesn't allow multiplication of two values with units, or division by them. I'm doing complex calculations on hsl values in the [Ion theme](https://github.com/zamsyt/obsidian-ion), and ended up having to add separate sliders for the HSL components.

- either just remove the %-signs from saturation and lightness
- or scale them to be decimal values between 0-1

### PR DESCRIPTION
**Pull request by zamsyt**
Resolves #91

### CODE REVIEW

**Comment by mgmeyers** [comment]
@zamsyt I'm not quite sure what this is used for. Could you clarify the use case and why `hsl-split` doesn't do the job?

**Comment by zamsyt** [comment]
@mgmeyers For example, I need to multiply the lightness by a pixel value (I do it for bloom calculations in Ion), eg:
```
calc(5px * var(--color-l))
```
`calc()` supports multiplication only if at least one of the values is unitless. This means I cannot use the lightness value from `hsl-split`, since CSS considers percents to be units.

I get it if you think this is too niche to add, but I'd very much like to be able to provide actual color inputs for further development of the theme :)

**Comment by zamsyt** [comment]
@mgmeyers You merged this somewhere but it's not in any of the releases. Is this a *yes* or a *no*? :grin:

**Comment by mgmeyers** [comment]
Ah, whoops, sorry @zamsyt . I looks like this got overwritten with the latest updates that mProjectsCode added. I'll look into adding them back in. Should have some time later this week. If you have some time before then to submit and update PR (the core code changed quite a bit recently) I'd be happy to merge it.

**Pull request merged**
